"""Public API for Project Simulation."""

from .acoustics import (
    HeardSound,
    HearingProfile,
    SoundEvent,
    count_sound_occluders,
    distance_attenuation_db,
    hear_sound,
    propagate_sound,
)
from .ambient import AmbientAgent, AmbientEvent, AmbientNPCSimulation
from .api import (
    CLASS_DEFINITIONS,
    ENEMY_DEFINITIONS,
    CombatEngine,
    UtilityDecisionPolicy,
    WorldStore,
    create_character,
    create_enemy,
    generate_world,
    load_game,
    run_encounter,
    save_game,
)
from .cognition import (
    Belief,
    CandidateAction,
    EmotionState,
    Goal,
    Memory,
    Mind,
    Relationship,
)
from .demographics import (
    MigrationResult,
    employed_population,
    fill_occupation,
    migrate,
    migration_pressure,
    settlement_attractiveness,
    unemployment_ratio,
)
from .dialogue import DialogueResult, converse, disposition_toward, find_belief
from .diplomacy import DiplomacyEngine, Treaty, TreatyStatus
from .doors import Door, PassageAxis
from .economy import (
    Commodity,
    Market,
    ProductionRecipe,
    ProductionResult,
    TradeResult,
    TradeRoute,
    run_production,
    transfer,
)
from .event_persistence import EventQueueStore
from .information import (
    Claim,
    Transmission,
    broadcast_claim,
    transmission_confidence,
    transmit_claim,
)
from .lod import AbstractActorState, ActorLODManager, abstract_actor, restore_actor
from .macro_checkpoint import MacroCheckpointStore
from .models import (
    Action,
    Actor,
    BodyPart,
    CombatMode,
    DamageType,
    EncounterResult,
    EncounterState,
    GameState,
    PlayerCharacter,
    WorldConfig,
    WorldMap,
)
from .navigation import (
    MovementResult,
    SweepHit,
    move_actor_with_collisions,
    sweep_doors,
    sweep_entity,
)
from .npc_controller import AgentDirective, GoalRequest, NPCController
from .physiology import (
    Container,
    Injury,
    InjuryType,
    Loadout,
    PhysicalItem,
    Physiology,
)
from .planning import Plan, PlanAction, Planner, WorldFact
from .projectiles import (
    Projectile,
    ProjectileHit,
    ProjectileSimulator,
    ProjectileSpec,
    ProjectileStep,
    ballistic_drop_m,
    impact_speed_from_energy,
    launch_velocity,
    sweep_projectile,
)
from .ranged import (
    RangedImpactResult,
    RangedWeapon,
    aim_point_for_body_part,
    resolve_projectile_impact,
)
from .rumors import RumorDelivery, RumorNetwork, SocialLink
from .schedules import RoutineBlock, RoutineDecision, RoutineSchedule
from .settlement_dynamics import (
    OccupationRecipe,
    SettlementDayResult,
    SettlementDynamics,
    SettlementEconomicProfile,
)
from .simulation import (
    FactionState,
    SettlementState,
    SimulationKernel,
    SimulationLOD,
    WorldState,
)
from .skills import (
    PracticeEvent,
    PracticeResult,
    SkillGain,
    SkillSet,
    SkillState,
    default_skill_transfers,
)
from .spatial import (
    Bounds,
    Observation,
    SpatialEntity,
    Vec3,
    VisionProfile,
    observe,
)
from .spatial_combat import (
    SpatialAttackResult,
    SpatialCombatant,
    SpatialCombatResolver,
    StrikeType,
    WeaponPhysics,
)
from .spatial_encounter import (
    SpatialAction,
    SpatialEncounterEngine,
    SpatialEncounterState,
    SpatialIntent,
    SpatialTurnEvent,
    SpatialTurnResult,
)
from .textui import narrative_view, render_observations, tactical_map
from .textworld import (
    CommandKind,
    CommandResult,
    ParsedCommand,
    TextWorldSession,
    build_demo_session,
    parse_command,
)
from .textworld_replay import TextWorldReplayStore, session_digest
from .worldstate import WorldActor
from .worldstate_persistence import WorldStateStore

__all__ = [
    "CLASS_DEFINITIONS",
    "ENEMY_DEFINITIONS",
    "Action",
    "propagate_sound",
    "hear_sound",
    "distance_attenuation_db",
    "count_sound_occluders",
    "SoundEvent",
    "HearingProfile",
    "HeardSound",
    "AmbientNPCSimulation",
    "AmbientEvent",
    "AmbientAgent",
    "restore_actor",
    "abstract_actor",
    "ActorLODManager",
    "AbstractActorState",
    "NPCController",
    "GoalRequest",
    "AgentDirective",
    "Actor",
    "Belief",
    "BodyPart",
    "Bounds",
    "CandidateAction",
    "unemployment_ratio",
    "settlement_attractiveness",
    "migration_pressure",
    "migrate",
    "fill_occupation",
    "employed_population",
    "MigrationResult",
    "TradeRoute",
    "TradeResult",
    "ProductionResult",
    "ProductionRecipe",
    "Market",
    "Commodity",
    "Claim",
    "parse_command",
    "build_demo_session",
    "TextWorldSession",
    "session_digest",
    "TextWorldReplayStore",
    "ParsedCommand",
    "CommandResult",
    "CommandKind",
    "CombatEngine",
    "CombatMode",
    "Container",
    "DamageType",
    "sweep_doors",
    "PassageAxis",
    "Door",
    "find_belief",
    "disposition_toward",
    "converse",
    "DialogueResult",
    "TreatyStatus",
    "Treaty",
    "DiplomacyEngine",
    "EmotionState",
    "EventQueueStore",
    "MacroCheckpointStore",
    "EncounterResult",
    "EncounterState",
    "FactionState",
    "GameState",
    "Goal",
    "Injury",
    "InjuryType",
    "Loadout",
    "Memory",
    "Mind",
    "sweep_entity",
    "move_actor_with_collisions",
    "SweepHit",
    "MovementResult",
    "Observation",
    "SettlementEconomicProfile",
    "SettlementDynamics",
    "SettlementDayResult",
    "OccupationRecipe",
    "Plan",
    "PlanAction",
    "Planner",
    "PhysicalItem",
    "sweep_projectile",
    "launch_velocity",
    "impact_speed_from_energy",
    "ballistic_drop_m",
    "ProjectileStep",
    "ProjectileSpec",
    "ProjectileSimulator",
    "ProjectileHit",
    "Projectile",
    "Physiology",
    "PlayerCharacter",
    "Relationship",
    "default_skill_transfers",
    "SkillState",
    "SkillSet",
    "SkillGain",
    "PracticeResult",
    "PracticeEvent",
    "resolve_projectile_impact",
    "aim_point_for_body_part",
    "RangedWeapon",
    "RangedImpactResult",
    "SocialLink",
    "RumorNetwork",
    "RumorDelivery",
    "RoutineBlock",
    "RoutineDecision",
    "RoutineSchedule",
    "SettlementState",
    "SimulationKernel",
    "SimulationLOD",
    "SpatialAttackResult",
    "SpatialTurnResult",
    "SpatialTurnEvent",
    "SpatialIntent",
    "SpatialEncounterState",
    "SpatialEncounterEngine",
    "SpatialAction",
    "SpatialCombatant",
    "SpatialCombatResolver",
    "SpatialEntity",
    "StrikeType",
    "Transmission",
    "UtilityDecisionPolicy",
    "Vec3",
    "VisionProfile",
    "WeaponPhysics",
    "WorldActor",
    "WorldConfig",
    "WorldFact",
    "WorldMap",
    "WorldState",
    "WorldStateStore",
    "WorldStore",
    "broadcast_claim",
    "create_character",
    "create_enemy",
    "generate_world",
    "load_game",
    "narrative_view",
    "observe",
    "render_observations",
    "run_encounter",
    "run_production",
    "save_game",
    "tactical_map",
    "transfer",
    "transmission_confidence",
    "transmit_claim",
]

__version__ = "1.1.0"
