"""Public API for Project Simulation."""

from .api import (
    CLASS_DEFINITIONS,
    ENEMY_DEFINITIONS,
    CombatEngine,
    UtilityDecisionPolicy,
    WorldStore,
    create_character,
    create_enemy,
    generate_world,
    load_game,
    run_encounter,
    save_game,
)
from .cognition import (
    Belief,
    CandidateAction,
    EmotionState,
    Goal,
    Memory,
    Mind,
    Relationship,
)
from .demographics import (
    MigrationResult,
    employed_population,
    fill_occupation,
    migrate,
    migration_pressure,
    settlement_attractiveness,
    unemployment_ratio,
)
from .diplomacy import DiplomacyEngine, Treaty, TreatyStatus
from .economy import (
    Commodity,
    Market,
    ProductionRecipe,
    ProductionResult,
    TradeResult,
    TradeRoute,
    run_production,
    transfer,
)
from .event_persistence import EventQueueStore
from .information import (
    Claim,
    Transmission,
    broadcast_claim,
    transmission_confidence,
    transmit_claim,
)
from .lod import AbstractActorState, ActorLODManager, abstract_actor, restore_actor
from .models import (
    Action,
    Actor,
    BodyPart,
    CombatMode,
    DamageType,
    EncounterResult,
    EncounterState,
    GameState,
    PlayerCharacter,
    WorldConfig,
    WorldMap,
)
from .npc_controller import AgentDirective, GoalRequest, NPCController
from .physiology import (
    Container,
    Injury,
    InjuryType,
    Loadout,
    PhysicalItem,
    Physiology,
)
from .planning import Plan, PlanAction, Planner, WorldFact
from .rumors import RumorDelivery, RumorNetwork, SocialLink
from .schedules import RoutineBlock, RoutineDecision, RoutineSchedule
from .settlement_dynamics import (
    OccupationRecipe,
    SettlementDayResult,
    SettlementDynamics,
    SettlementEconomicProfile,
)
from .simulation import (
    FactionState,
    SettlementState,
    SimulationKernel,
    SimulationLOD,
    WorldState,
)
from .spatial import (
    Bounds,
    Observation,
    SpatialEntity,
    Vec3,
    VisionProfile,
    observe,
)
from .spatial_encounter import (
    SpatialAction,
    SpatialEncounterEngine,
    SpatialEncounterState,
    SpatialIntent,
    SpatialTurnEvent,
    SpatialTurnResult,
)
from .spatial_combat import (
    SpatialAttackResult,
    SpatialCombatant,
    SpatialCombatResolver,
    StrikeType,
    WeaponPhysics,
)
from .textui import narrative_view, render_observations, tactical_map
from .worldstate import WorldActor
from .worldstate_persistence import WorldStateStore

__all__ = [
    "CLASS_DEFINITIONS",
    "ENEMY_DEFINITIONS",
    "Action",
    "restore_actor",
    "abstract_actor",
    "ActorLODManager",
    "AbstractActorState",
    "NPCController",
    "GoalRequest",
    "AgentDirective",
    "Actor",
    "Belief",
    "BodyPart",
    "Bounds",
    "CandidateAction",
    "unemployment_ratio",
    "settlement_attractiveness",
    "migration_pressure",
    "migrate",
    "fill_occupation",
    "employed_population",
    "MigrationResult",
    "TradeRoute",
    "TradeResult",
    "ProductionResult",
    "ProductionRecipe",
    "Market",
    "Commodity",
    "Claim",
    "CombatEngine",
    "CombatMode",
    "Container",
    "DamageType",
    "TreatyStatus",
    "Treaty",
    "DiplomacyEngine",
    "EmotionState",
    "EventQueueStore",
    "EncounterResult",
    "EncounterState",
    "FactionState",
    "GameState",
    "Goal",
    "Injury",
    "InjuryType",
    "Loadout",
    "Memory",
    "Mind",
    "Observation",
    "SettlementEconomicProfile",
    "SettlementDynamics",
    "SettlementDayResult",
    "OccupationRecipe",
    "Plan",
    "PlanAction",
    "Planner",
    "PhysicalItem",
    "Physiology",
    "PlayerCharacter",
    "Relationship",
    "SocialLink",
    "RumorNetwork",
    "RumorDelivery",
    "RoutineBlock",
    "RoutineDecision",
    "RoutineSchedule",
    "SettlementState",
    "SimulationKernel",
    "SimulationLOD",
    "SpatialAttackResult",
    "SpatialTurnResult",
    "SpatialTurnEvent",
    "SpatialIntent",
    "SpatialEncounterState",
    "SpatialEncounterEngine",
    "SpatialAction",
    "SpatialCombatant",
    "SpatialCombatResolver",
    "SpatialEntity",
    "StrikeType",
    "Transmission",
    "UtilityDecisionPolicy",
    "Vec3",
    "VisionProfile",
    "WeaponPhysics",
    "WorldActor",
    "WorldConfig",
    "WorldFact",
    "WorldMap",
    "WorldState",
    "WorldStateStore",
    "WorldStore",
    "broadcast_claim",
    "create_character",
    "create_enemy",
    "generate_world",
    "load_game",
    "narrative_view",
    "observe",
    "render_observations",
    "run_encounter",
    "run_production",
    "save_game",
    "tactical_map",
    "transfer",
    "transmission_confidence",
    "transmit_claim",
]

__version__ = "1.1.0"
